#!/usr/bin/env node
/*
 * Design token pipeline: tokens/*.json (DTCG, synced from Figma by Tokens Studio)
 * → Style Dictionary → the two files the site and the design gate consume:
 *   styles/pulse-tokens.css      CSS custom properties (base, plus compact overrides ≤ tablet)
 *   reference/design-tokens.json lightweight JSON of every token, for checks and tools
 *
 *   node tokens/build.mjs           write both files
 *   node tokens/build.mjs --check   exit 1 if the committed files differ from the tokens
 *
 * The site has no build step, so the outputs are committed; CI proves they're in sync.
 */
import StyleDictionary from 'style-dictionary'; // eslint-disable-line import/no-unresolved -- ESM-only exports map
import { readFileSync, writeFileSync } from 'node:fs';

const OUT = { css: 'styles/pulse-tokens.css', json: 'reference/design-tokens.json' };

/** Any colour to the notation stylelint-config-standard expects; other values unchanged. */
export function normalize(value) {
  if (value && typeof value === 'object' && 'value' in value && 'unit' in value) return `${value.value}${value.unit}`;
  const v = String(value).trim();
  const hex = v.match(/^#([0-9a-f]{3}|[0-9a-f]{6})$/i);
  if (hex) {
    const h = hex[1].toLowerCase();
    return h.length === 6 && h[0] === h[1] && h[2] === h[3] && h[4] === h[5] ? `#${h[0]}${h[2]}${h[4]}` : `#${h}`;
  }
  const rgba = v.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+%?)\s*)?\)$/i);
  if (rgba) {
    const [, r, g, b, a] = rgba;
    if (a === undefined) return `rgb(${r} ${g} ${b})`;
    const pct = a.endsWith('%') ? a : `${Math.round(parseFloat(a) * 100)}%`;
    return `rgb(${r} ${g} ${b} / ${pct})`;
  }
  return v;
}

/** Leaf tokens of a DTCG tree: [{ name, group, value, type }], in file order. */
export function leaves(tree, group = null, inheritedType = undefined) {
  const out = [];
  Object.entries(tree).forEach(([key, node]) => {
    if (key.startsWith('$') || !node || typeof node !== 'object') return;
    const type = node.$type || inheritedType;
    if ('$value' in node) {
      out.push({
        name: key, group, value: normalize(node.$value), type,
      });
    } else out.push(...leaves(node, group || key, type));
  });
  return out;
}

const read = (f) => JSON.parse(readFileSync(f, 'utf8'));

/** Formats the CSS from the resolved base tokens plus the compact overrides. */
export function formatCss(base, compact, groups, tabletMax) {
  const lines = [
    '/*',
    ' * PULSE design tokens. GENERATED by tokens/build.mjs from tokens/*.json',
    ' * (Figma → Tokens Studio → GitHub). Don\'t edit here: change the token in',
    ' * Figma, or in tokens/*.json, then run `npm run tokens`.',
    ' */',
    '',
    ':root {',
  ];
  let last = null;
  base.forEach((t) => {
    if (t.group !== last) {
      if (last) lines.push('');
      lines.push(`  /* ${groups[t.group] || t.group} */`);
      last = t.group;
    }
    lines.push(`  --pulse-${t.name}: ${t.value};`);
  });
  lines.push('}', '', `@media (width <= ${tabletMax}) {`, '  :root {');
  compact.forEach((t) => lines.push(`    --pulse-${t.name}: ${t.value};`));
  lines.push('  }', '}', '');
  return lines.join('\n');
}

export async function build() {
  const baseTree = read('tokens/base.json');
  const compactTree = read('tokens/compact.json');
  // Style Dictionary resolves references ({color.ink}) and validates the DTCG tree
  const sd = new StyleDictionary({
    source: ['tokens/base.json'],
    log: { verbosity: 'silent', warnings: 'disabled' },
    platforms: { json: { transforms: ['name/kebab'], files: [{ destination: 'tokens.json', format: 'json/nested' }] } },
  });
  const [{ output }] = await sd.formatPlatform('json');
  const resolved = JSON.parse(output);
  const base = leaves(baseTree).map((t) => {
    const r = resolved[t.group][t.name];
    if (t.type === 'typography') return { ...t, value: Object.fromEntries(Object.entries(r).map(([k, v]) => [k, normalize(v)])) };
    return { ...t, value: normalize(r && typeof r === 'object' && !('unit' in r) ? r.value : r) };
  });
  const cssTokens = base.filter((t) => t.group !== 'breakpoint' && t.type !== 'typography');
  const compact = leaves(compactTree);
  const known = new Set(base.map((t) => t.name));
  compact.forEach((t) => { if (!known.has(t.name)) throw new Error(`compact token "${t.name}" has no base token`); });
  const groups = Object.fromEntries(Object.entries(baseTree).map(([k, v]) => [k, v.$description || k]));
  const bp = Object.fromEntries(base.filter((t) => t.group === 'breakpoint').map((t) => [t.name, t.value]));
  const css = formatCss(cssTokens, compact, groups, bp.tablet);
  const json = `${JSON.stringify({
    $comment: 'GENERATED by tokens/build.mjs from tokens/*.json (Figma → Tokens Studio). Every token, as CSS-ready values.',
    source: { figmaFile: 'dbJRnntnVQz6IEF1cqUGeA', tokens: ['tokens/base.json', 'tokens/compact.json'] },
    note: baseTree.$description,
    base: Object.fromEntries(cssTokens.map((t) => [t.name, t.value])),
    typography: Object.fromEntries(base.filter((t) => t.type === 'typography').map((t) => [t.name, t.value])),
    compact: Object.fromEntries(compact.map((t) => [t.name, t.value])),
    compactBelow: bp.tablet,
    breakpoints: bp,
  }, null, 2)}\n`;
  return { css, json };
}

if (process.argv[1] && process.argv[1].endsWith('build.mjs')) {
  const { css, json } = await build();
  if (process.argv.includes('--check')) {
    const stale = [[OUT.css, css], [OUT.json, json]].filter(([f, want]) => readFileSync(f, 'utf8') !== want).map(([f]) => f);
    if (stale.length) {
      console.error(`Out of date with tokens/*.json: ${stale.join(', ')}. Run \`npm run tokens\` and commit.`);
      process.exit(1);
    }
    console.log('design tokens: generated files are in sync');
  } else {
    writeFileSync(OUT.css, css);
    writeFileSync(OUT.json, json);
    console.log(`wrote ${OUT.css} and ${OUT.json}`);
  }
}
